name: Test Actions Python
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
      fail-fast: false

    steps:
      - name: Copia os arquivos do repo
        uses: actions/checkout@v4

      - name: Instalar o Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Instalar o biblioteca
        run: |
          python -m pip install --upgrade pip
          make install
      - name: Verificar formação dos arquivos
        run: |
          make format
      - name: Verificar lint dos arquivos
        run: |
          make lint
      - name: Verificar tipagem dos arquivos
        run: |
          make pyright
      - name: Verificar testes dos arquivos
        run: |
          make test
        env:
            FRED_API_KEY : ${{ secrets.FRED_API_KEY }}
